spring.application.name=gramconnect

server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gramconnect_db
spring.datasource.username=postgres
spring.datasource.password=Umiabiha@69
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# JWT
jwt.secret=GramConnectSuperSecretKeyForDevelopmentOnly123456789
jwt.expiration=86400000